version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

